export const emojiMap: Record<number, { src: string; label: string }> = {
  1: { src: '/icons/community/emojis/smile.svg', label: '스마일' },
  2: { src: '/icons/community/emojis/loveEyes.svg', label: '눈하트' },
  3: { src: '/icons/community/emojis/tongue.svg', label: '메롱' },
  4: { src: '/icons/community/emojis/surprised.svg', label: '놀람' },
  5: { src: '/icons/community/emojis/moneyMouth.svg', label: '머니' },
  6: { src: '/icons/community/emojis/partyFace.svg', label: '축하' },
  7: { src: '/icons/community/emojis/thumbsUp.svg', label: '좋아요' },
  8: { src: '/icons/community/emojis/pray.svg', label: '감사해요' },
  9: { src: '/icons/community/emojis/fingerHeart.svg', label: '손하트' },
  10: { src: '/icons/community/emojis/victory.svg', label: '브이' },
  11: { src: '/icons/community/emojis/heartHands.svg', label: '하트손' },
  12: { src: '/icons/community/emojis/hundred.svg', label: '100점' },
  13: { src: '/icons/community/emojis/question.svg', label: '놀람+궁금' },
  14: { src: '/icons/community/emojis/loveRibbon.svg', label: '선물' },
  15: { src: '/icons/community/emojis/medal.svg', label: '메달' },
  16: { src: '/icons/community/emojis/rose.svg', label: '장미' },
  17: { src: '/icons/community/emojis/partyPopper.svg', label: '폭죽' },
  18: { src: '/icons/community/emojis/rice.svg', label: '밥' },
  19: { src: '/icons/community/emojis/sandwitch.svg', label: '김밥' },
  20: { src: '/icons/community/emojis/salad.svg', label: '샐러드' },
  21: { src: '/icons/community/emojis/chicken.svg', label: '치킨' },
  22: { src: '/icons/community/emojis/burger.svg', label: '버거' },
  23: { src: '/icons/community/emojis/pizza.svg', label: '피자' },
};
